version: "3.9"

services:
  api:
    build: .
    container_name: flask-api
    restart: always
    ports:
      - "5555:5555"
    command: >
      sh -c "service cron start && python3 ./dam_api/app.py"
    volumes:
      - .:/usr/src/app